language: node_js
node_js:
  - "6"

script:
  - yarn install
  - yarn test-ci
  - yarn build
#  - NODE_ENV=production node -e 'require("./services/Lambda.js").handler({}, { succeed: ()=>{} })' || exit 1

deploy:
  skip_cleanup: true # keep build
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email:
    on_success: change
    on_failure: always
