language: node_js
node_js:
  - "6"

script:
  - yarn install
  - yarn test-ci
  - yarn build
#  - NODE_ENV=production node -e 'require("./services/Lambda.js").handler({}, { succeed: ()=>{} })' || exit 1
  - yarn install --production
  - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
  - serverless deploy --verbose # TODO: master only
  - curl -s --head  --request GET https://adeira.cz | grep "200 OK" > /dev/null || exit 1

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email:
    on_success: change
    on_failure: always
